# Generated by Django 5.1.2 on 2024-12-10 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('client_admin', 'Client Admin'), ('team_member', 'Team Member'), ('user', 'User'), ('interviewer', 'Interviewer'), ('agency', 'Agency')], default='user', max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(help_text="User's Full Name", max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
