# Generated by Django 5.1.2 on 2024-12-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userprofile_organization'),
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'phone'], name='core_user_email_96e900_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['name'], name='core_userpr_name_a226f4_idx'),
        ),
    ]
