from dashboard.Views import (
    ClientUserView,
    ResumePraserView,
    InternalClientView,
    InternalClientDetailsView,
    InterviewerView,
    InterviewerDetails,
    ClientInvitationActivateView,
    CandidateView,
    EngagementTemplateView,
    EngagementView,
    EngagementOperationView,
    JobView,
    InterviewerAvailabilityView,
    PotentialInterviewerAvailabilityForCandidateView,
    InterviewerReqeustView,
    InterviewerRequestResponseView,
)
