# Generated by Django 5.1.2 on 2024-11-10 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('user_type', models.CharField(blank=True, max_length=2, null=True)),
                ('job_assigned', models.CharField(blank=True, choices=[('sde3', 'SDE III'), ('pe', 'PE'), ('sde2', 'SDE II'), ('devops1', 'DevOps I'), ('em', 'EM'), ('sdet2', 'SDET II'), ('sdet1', 'SDET I')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
