# Generated by Django 5.1.2 on 2024-11-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='user_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
