# Generated by Django 5.1.2 on 2024-11-27 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_clientuser_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_registered_name', models.CharField(max_length=255)),
                ('website', models.URLField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('gstin', models.CharField(max_length=15)),
                ('pan', models.CharField(max_length=10)),
                ('signed_or_not', models.CharField(choices=[('Signed', 'Signed'), ('Not Signed', 'Not Signed')], max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientPointOfContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_of_contact', to='dashboard.internalclient')),
            ],
        ),
    ]
