# Generated by Django 5.1.2 on 2024-12-03 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_internalclient_clientpointofcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalInterviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('current_company', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_company', models.CharField(blank=True, max_length=255, null=True)),
                ('current_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('total_experience_years', models.IntegerField(default=0)),
                ('total_experience_months', models.IntegerField(default=0)),
                ('interview_experience_years', models.IntegerField(default=0)),
                ('interview_experience_months', models.IntegerField(default=0)),
                ('assigned_roles', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('strength', models.CharField(blank=True, max_length=50, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='interviewer_cvs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='clientpointofcontact',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientpointofcontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientpointofcontact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='internalclient',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internalclient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='internalclient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
