# Generated by Django 5.1.2 on 2024-12-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_internalinterviewer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalinterviewer',
            name='user',
        ),
    ]
