# Generated by Django 5.1.2 on 2024-12-08 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_internalinterviewer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpointofcontact',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_of_contact', to='dashboard.internalclient'),
        ),
    ]
