# Generated by Django 5.1.2 on 2024-12-16 05:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_clientpointofcontact_client'),
        ('organizations', '0006_alter_organization_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalclient',
            name='client_registered_name',
        ),
        migrations.AddField(
            model_name='internalclient',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internalclient',
            name='organization',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='internal_client', to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internalclient',
            name='address',
            field=models.TextField(blank=True, default='Hello'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internalclient',
            name='assigned_to',
            field=models.CharField(blank=True, default='nothing', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internalclient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internalclient',
            name='domain',
            field=models.CharField(blank=True, default='me', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internalclient',
            name='gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='internalclient',
            name='pan',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='internalclient',
            name='signed_or_not',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='internalclient',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internalclient',
            name='website',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
