# Generated by Django 5.1.2 on 2024-12-16 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_internalclient_client_registered_name_and_more'),
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalclient',
            name='user',
        ),
        migrations.AddField(
            model_name='internalinterviewer',
            name='organization',
            field=models.ManyToManyField(blank=True, related_name='interviewers', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='clientpointofcontact',
            name='client',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='points_of_contact', to='dashboard.internalclient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientpointofcontact',
            name='email_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='clientpointofcontact',
            name='mobile_no',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='internalinterviewer',
            name='current_company',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internalinterviewer',
            name='current_designation',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internalinterviewer',
            name='cv',
            field=models.FileField(blank=True, default='', upload_to='interviewer_cvs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internalinterviewer',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='internalinterviewer',
            name='previous_company',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internalinterviewer',
            name='strength',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
