# Generated by Django 5.1.2 on 2024-12-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_clientpointofcontact_email_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internalclient',
            old_name='signed_or_not',
            new_name='is_signed',
        ),
    ]
