# Generated by Django 5.1.2 on 2024-12-16 17:46

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_rename_signed_or_not_internalclient_is_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpointofcontact',
            name='mobile_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='IN', unique=True),
        ),
    ]
