# Generated by Django 5.1.2 on 2024-12-16 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_clientpointofcontact_mobile_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientpointofcontact',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='clientpointofcontact',
            old_name='mobile_no',
            new_name='phone',
        ),
    ]
