# Generated by Django 5.1.2 on 2024-12-20 15:17

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_rename_email_id_clientpointofcontact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalinterviewer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='IN', unique=True),
        ),
    ]
