# Generated by Django 5.1.2 on 2024-12-20 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_internalinterviewer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalinterviewer',
            name='interview_experience_months',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='internalinterviewer',
            name='interview_experience_years',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Expereince should be more than 1 year'), django.core.validators.MaxValueValidator(50, message='Enter a valid Experience')]),
        ),
        migrations.AlterField(
            model_name='internalinterviewer',
            name='strength',
            field=models.CharField(blank=True, choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('devops', 'DevOps'), ('testing', 'Strength'), ('aiml', 'AI/ML'), ('data_engineer', 'Data Engineer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='internalinterviewer',
            name='total_experience_months',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='internalinterviewer',
            name='total_experience_years',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Expereince should be more than 1 year'), django.core.validators.MaxValueValidator(50, message='Enter a valid Experience')]),
        ),
    ]
