# Generated by Django 5.1.2 on 2025-01-06 13:22

import django.db.models.deletion
import django.utils.timezone
import hiringdogbackend.ModelUtils
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0016_alter_internalinterviewer_interview_experience_months_and_more",
        ),
        ("organizations", "0006_alter_organization_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientuser",
            name="archived",
        ),
        migrations.RemoveField(
            model_name="clientuser",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="clientuser",
            name="job_assigned",
        ),
        migrations.RemoveField(
            model_name="clientuser",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="clientuser",
            name="user",
        ),
        migrations.RemoveField(
            model_name="clientuser",
            name="user_type",
        ),
        migrations.AddField(
            model_name="clientuser",
            name="Organization",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientuser",
                to="organizations.organization",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clientuser",
            name="designation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="clientuser",
            name="reason_for_archived",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PF", "Postition Filled"),
                    ("POH", "Position On Hold"),
                    ("OTH", "Other"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="clientuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("super_admin", "Super Admin"),
                    ("moderator", "Moderator"),
                    ("client_admin", "Client Admin"),
                    ("client_user", "Client User"),
                    ("user", "User"),
                    ("interviewer", "Interviewer"),
                    ("agency", "Agency"),
                ],
                max_length=15,
                verbose_name="user_type",
            ),
        ),
        migrations.AlterField(
            model_name="clientuser",
            name="email",
            field=models.EmailField(blank=True, default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="clientuser",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="candidate experience total year"
                    ),
                ),
                (
                    "month",
                    models.PositiveBigIntegerField(
                        default=0, help_text="candidate experience total month"
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region="IN"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=255)),
                ("company", models.CharField(blank=True, max_length=100)),
                ("designation", models.CharField(blank=True, max_length=100)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="From Which side this candidate is ?",
                        max_length=100,
                    ),
                ),
                ("cv", models.FileField(upload_to="candidate_cvs")),
                ("remark", models.TextField(blank=True, max_length=255, null=True)),
                ("specialization", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REC", "Recommended"),
                            ("NREC", "Not Recommended"),
                            ("SCH", "Schedule"),
                            ("NSCH", "Not Schedule"),
                        ],
                        default="NSCH",
                        help_text="candidate interview status",
                        max_length=15,
                    ),
                ),
                (
                    "reason_for_dropping",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CNI", "Candidate Not Interested"),
                            ("CNA", "Candidate Not Available"),
                            ("CNR", "Candidate Not Respond"),
                            ("OTH", "Others"),
                        ],
                        max_length=100,
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("total_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate",
                        to="organizations.organization",
                    ),
                ),
            ],
            bases=(
                models.Model,
                hiringdogbackend.ModelUtils.CreateUpdateDateTimeAndArchivedField,
            ),
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REC", "Recommended"),
                            ("NREC", "Not Recommended"),
                            ("SCH", "Schedule"),
                            ("NSCH", "Not Schedule"),
                        ],
                        help_text="Interview status",
                        max_length=15,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(help_text="Scheduled interview date and time"),
                ),
                (
                    "reschedule",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the interview has been rescheduled",
                    ),
                ),
                (
                    "recording",
                    models.FileField(
                        blank=True,
                        help_text="Interview recording file",
                        null=True,
                        upload_to="interview_recordings",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, help_text="Feedback for the candidate", null=True
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("total_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="interview",
                        to="dashboard.candidate",
                    ),
                ),
                (
                    "interivewer",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="interviews",
                        to="dashboard.internalinterviewer",
                    ),
                ),
            ],
            bases=(
                models.Model,
                hiringdogbackend.ModelUtils.CreateUpdateDateTimeAndArchivedField,
            ),
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("job_id", models.CharField(blank=True, max_length=100, null=True)),
                ("total_positions", models.PositiveSmallIntegerField(default=0)),
                (
                    "job_description_file",
                    models.FileField(upload_to="job_descriptions"),
                ),
                ("mandatory_skills", models.TextField(blank=True)),
                ("interview_time", models.CharField(max_length=50)),
                ("other_details", models.JSONField(blank=True, default=dict)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruiter",
                        to="dashboard.clientuser",
                    ),
                ),
                (
                    "hiring_manager",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hiringmanager",
                        to="dashboard.clientuser",
                    ),
                ),
            ],
            bases=(
                models.Model,
                hiringdogbackend.ModelUtils.CreateUpdateDateTimeAndArchivedField,
            ),
        ),
        migrations.AddField(
            model_name="clientuser",
            name="User",
            field=models.OneToOneField(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientuser",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
